### ISSUE TITLE
why tflearn?

### ISSUE THREAD

**Issue by cgh2797** [Shen-Lab/DeepAffinity#4]
tflearn is no longer updated, it only supports tf1 and now it seems to be abandoned.
Why did you use tflearn when writing code?

Is it because you like tflearn?

**Comment by Shen-Lab** [comment]
Thank you for your interest in DeepAffinity!  Per your question, our project started in 2017 when the sphere of deep learning libraries was very different from now.  It has indeed changed a lot and tflearn was last updated more than a year ago.  We migrate to keras and hope to update DeepAffinity in future.  If you prefer anything else, we would be interested in hearing your opinions!

**Comment by cgh2797** [comment]
Thanks for the answer, I hope you migrated to keras well
