### ISSUE TITLE
Checkpoint for ki dataset

### ISSUE THREAD

**Issue by ryan-224** [Shen-Lab/DeepAffinity#5]
Hi,

Thanks for sharing this great work.

Is it true that the checkpoints you provided are for IC-50 dataset only? If yes, do you have checkpoints for ki dataset as well?

Thank you!

**Comment by mostafakarimi71** [comment]
Hi,

Thanks for your interest in our paper. I have uploaded the checkpoints for both Kd and Ki datasets.

If you have any other questions, please let us know.

**Comment by ryan-224** [comment]
Thank you so much!
